apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: faroldoinvestimento
  name: faroldoinvestimento-site-tls-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: www.faroldoinvestimento.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: faroldoinvestimento-site
                port:
                  number: 5678
  tls:
    - secretName: faroldoinvestimento-tls
      hosts:
        - www.faroldoinvestimento.com.br